spring:
  datasource:
    url: jdbc:mysql://43.201.188.14:3306/securityapi
    username: shinjw
    password: shinjwpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
    database: mysql

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 5000

# 아래 정보는 ClientRegistration에 저장됨
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 8188129273-lu2omksjkre2mvivus8cpdv05oqknbdq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: 5h4gZ6dxrMD3wDhDSIyc
            client-secret: L8eCcIloQL
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate:
      SQL: debug
  #    type: trace


decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

my-jwt:
  secret: gyJvbh66SjHHBwfVTAw5mOnG_W0LlyIft8aBM-Oz9ws
  accessExpirationTime: 180_000
  refreshExpirationTime: 720_000

---
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 60000