spring:
  datasource:
    url: jdbc:mysql://43.201.188.14:3306/securityapi
    username: shinjw
    password: shinjwpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
    database: mysql

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 60000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 8188129273-lu2omksjkre2mvivus8cpdv05oqknbdq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

logging:
  level:
    org.hibernate:
      SQL: debug
  #    type: trace


decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

my-jwt:
  secret: gyJvbh66SjHHBwfVTAw5mOnG_W0LlyIft8aBM-Oz9ws
  accessExpirationTime: 180_000
  refreshExpirationTime: 720_000

---
spring:
  profiles:
    active: prod

  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 60000