spring:
  datasource:
    url: jdbc:mysql://43.201.188.14:3306/securityapi
    username: shinjw
    password: shinjwpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
    database: mysql

logging:
  level:
    org.hibernate:
      SQL: debug
  #    type: trace


decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

my-jwt:
  secret: gyJvbh66SjHHBwfVTAw5mOnG_W0LlyIft8aBM-Oz9ws
  accessExpirationTime: 180_000
  refreshExpirationTime: 86_400_000